version: '3.9'

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: character_AI_bot
    ports:
      - 5432:5432
    volumes:
      - ./.pg_data/:/var/lib/postgresql/data
