version: '2.2'

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: character_AI_bot
    ports:
    - 5432:5432
    volumes:
    - ./.pg_data/:/var/lib/postgresql/data
    networks:
    - web

  web_app:
    build:
      context: .
      dockerfile: web_app/Dockerfile
    restart: on-failure
    ports:
    - 5000:5000
    networks:
    - web
    depends_on:
    - postgres

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: on-failure
    networks:
    - web
    depends_on:
    - postgres

networks:
  web:
    name: web